color: purple
description: null
fieldLayouts:
  52e2e29c-5bdc-4619-944a-d80918f22262:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-11-21T11:59:33+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 575507f4-024a-49e7-84fe-5ff5dcb45b3a
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-11-21T12:01:22+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: eb46378c-fdcd-4b50-8a77-2dd98f76dffe # Link field
            handle: null
            includeInCards: false
            instructions: null
            label: Link
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 95d801fe-ca87-4f6e-8adc-6880984e022d
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: 4f2ea20b-5d11-4134-91b9-06a53c567254
        userCondition: null
handle: navigationItem
hasTitleField: true
icon: bars
name: 'Navigation item'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
