color: orange
description: null
fieldLayouts:
  280d93cb-cba1-4319-9e38-32c697f45980:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-11-21T12:12:01+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 218931a2-5461-42bb-ae6d-baedc580e83b
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-11-21T12:13:57+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: eb46378c-fdcd-4b50-8a77-2dd98f76dffe # Link field
            handle: buttonLink
            includeInCards: false
            instructions: null
            label: 'Button link'
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2418b6c5-adfe-4966-8445-0695f65baa85
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: 16caae7b-b79e-46fa-90c4-5ab41f7c8e0b
        userCondition: null
handle: universalMatrixButton
hasTitleField: true
icon: circle-dot
name: Tlaƒçidlo
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
