headingLevels:
  - 2
  - 3
name: Extended
options:
  alignment:
    options:
      - left
      - right
      - center
toolbar:
  - heading
  - '|'
  - bold
  - italic
  - '|'
  - alignment
  - bulletedList
  - numberedList
  - link
