altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  8da8af32-2ede-48a4-8776-ac240d6f83c8:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-11-21T11:57:30+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 2ab855a4-353c-47e9-9879-698c561c54b4
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 40596554-20fe-415d-be25-18db375bf1f8
        userCondition: null
fs: pictures
handle: pictures
name: Pictures
sortOrder: 1
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: pictures
transformSubpath: ''
