columnSuffix: null
handle: textMultiline
instructions: null
name: 'Text multiline'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 3
  multiline: true
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: site
type: craft\fields\PlainText
