columnSuffix: null
handle: universalMatrix
instructions: null
name: 'Universal matrix'
searchable: false
settings:
  createButtonLabel: null
  defaultIndexViewMode: cards
  enableVersioning: false
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - 0949937c-0ca6-4e45-ad21-3015403228aa # Titul
        -
          - group
          - General
    -
      __assoc__:
        -
          - uid
          - 3620f296-fa12-4a20-a4ff-50afb9378f68 # Text
        -
          - group
          - General
    -
      __assoc__:
        -
          - uid
          - 4ee7bbf1-00f5-4854-af48-28546bfe0e52 # Text s obrázkom
        -
          - group
          - General
    -
      __assoc__:
        -
          - uid
          - 15aaa04b-97c0-4a69-8fd8-63f04b2faa87 # Obrázok
        -
          - group
          - General
    -
      __assoc__:
        -
          - uid
          - 68f5ac63-9691-4d0d-bc4b-c599e04a1787 # Galéria
        -
          - group
          - General
    -
      __assoc__:
        -
          - uid
          - 02663346-777f-4ddc-b6bf-19e9887bd398 # Tlačidlo
        -
          - group
          - General
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: 50
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: cards
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
