defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 58da1196-3e88-4629-80d2-35907441a03e # Homepage
handle: homepage
maxAuthors: 1
name: Homepage
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  5c4bfb49-f023-4c60-9d65-1509715c2acc: # GW Hotel HU
    enabledByDefault: true
    hasUrls: true
    template: pages/index.twig
    uriFormat: homepage
  a68ab4b9-3cd1-41ad-bc0a-45223018a5c0: # GW Hotel
    enabledByDefault: true
    hasUrls: true
    template: pages/index.twig
    uriFormat: homepage
type: single
