defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 722afe03-8eea-4e09-988f-f7cc536575b7 # Universal
handle: universal
maxAuthors: 1
name: Universal
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  5c4bfb49-f023-4c60-9d65-1509715c2acc: # GW Hotel HU
    enabledByDefault: true
    hasUrls: true
    template: pages/universal.twig
    uriFormat: '{slug}'
  a68ab4b9-3cd1-41ad-bc0a-45223018a5c0: # GW Hotel
    enabledByDefault: true
    hasUrls: true
    template: pages/universal.twig
    uriFormat: '{slug}'
structure:
  maxLevels: 1
  uid: 353f7d9a-c6c3-46d6-aaec-6f76e62db01e
type: structure
